-- NovaSalud: esquema alineado con Laravel (especialidades, médicos, servicios, citas, solicitudes, IA).
-- Para un solo origen de datos: en backend/api/.env usa DB_CONNECTION=pgsql apuntando a este proyecto Supabase
-- y ejecuta `php artisan migrate` (las migraciones Laravel omiten tablas que ya existan).
-- Ejecutar con: supabase db push / migración en el panel SQL de Supabase.

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------------
create table public.especialidades (
  id bigint generated by default as identity primary key,
  nombre text not null,
  imagen text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_especialidades_updated_at
  before update on public.especialidades
  for each row
  execute function public.handle_updated_at();

create table public.medicos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  dni text unique,
  especialidad_id bigint not null references public.especialidades (id) on delete cascade,
  foto text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index medicos_especialidad_id_idx on public.medicos (especialidad_id);

create trigger trg_medicos_updated_at
  before update on public.medicos
  for each row
  execute function public.handle_updated_at();

create table public.servicios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text not null,
  precio numeric(8, 2) not null,
  medico_id bigint not null references public.medicos (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index servicios_medico_id_idx on public.servicios (medico_id);

create trigger trg_servicios_updated_at
  before update on public.servicios
  for each row
  execute function public.handle_updated_at();

create table public.solicitudes_citas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  paciente_dni text,
  paciente_direccion text,
  telefono text not null,
  email text,
  especialidad text,
  medico_id bigint references public.medicos (id) on delete set null,
  fecha date,
  hora time,
  motivo text,
  motivo_cancelacion text,
  estado text not null default 'nueva',
  origen text not null default 'web',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index solicitudes_citas_estado_idx on public.solicitudes_citas (estado);

create trigger trg_solicitudes_citas_updated_at
  before update on public.solicitudes_citas
  for each row
  execute function public.handle_updated_at();

create table public.citas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  servicio_id bigint not null references public.servicios (id) on delete cascade,
  fecha date not null,
  hora time not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index citas_user_id_idx on public.citas (user_id);

create trigger trg_citas_updated_at
  before update on public.citas
  for each row
  execute function public.handle_updated_at();

create table public.ai_interaction_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  user_id uuid references auth.users (id) on delete set null,
  solicitud_cita_id bigint references public.solicitudes_citas (id) on delete set null,
  model text not null,
  input_sha256 char(64) not null,
  input_length integer not null,
  result jsonb,
  prompt_tokens integer,
  completion_tokens integer,
  latency_ms integer,
  ok boolean not null default false,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index ai_interaction_logs_created_at_idx on public.ai_interaction_logs (created_at);
create index ai_interaction_logs_action_idx on public.ai_interaction_logs (action);

create trigger trg_ai_interaction_logs_updated_at
  before update on public.ai_interaction_logs
  for each row
  execute function public.handle_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.especialidades enable row level security;
alter table public.medicos enable row level security;
alter table public.servicios enable row level security;
alter table public.solicitudes_citas enable row level security;
alter table public.citas enable row level security;
alter table public.ai_interaction_logs enable row level security;

-- Catálogo público (sitio web sin login)
create policy "especialidades_select_public"
  on public.especialidades for select
  to anon, authenticated
  using (true);

create policy "medicos_select_public"
  on public.medicos for select
  to anon, authenticated
  using (true);

create policy "servicios_select_public"
  on public.servicios for select
  to anon, authenticated
  using (true);

-- Formulario de cita: inserción anónima
create policy "solicitudes_citas_insert_public"
  on public.solicitudes_citas for insert
  to anon, authenticated
  with check (true);

-- Gestión interna: usuarios autenticados (refinar a rol admin en producción)
create policy "especialidades_write_authenticated"
  on public.especialidades for all
  to authenticated
  using (true)
  with check (true);

create policy "medicos_write_authenticated"
  on public.medicos for all
  to authenticated
  using (true)
  with check (true);

create policy "servicios_write_authenticated"
  on public.servicios for all
  to authenticated
  using (true)
  with check (true);

create policy "solicitudes_citas_all_authenticated"
  on public.solicitudes_citas for all
  to authenticated
  using (true)
  with check (true);

create policy "citas_own_data"
  on public.citas for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "ai_logs_insert_authenticated"
  on public.ai_interaction_logs for insert
  to authenticated
  with check (user_id is null or user_id = auth.uid());

create policy "ai_logs_select_own"
  on public.ai_interaction_logs for select
  to authenticated
  using (user_id is null or user_id = auth.uid());
