-- Tablas de autenticación Laravel (login, registro, reset de contraseña).
-- Misma base que usa backend/api con DB_CONNECTION=pgsql.
-- Si ya ejecutaste `php artisan migrate`, estas tablas pueden existir; el script es idempotente.

-- ---------------------------------------------------------------------------
-- users (cuentas paciente / administrador)
-- ---------------------------------------------------------------------------
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  email_verified_at timestamptz,
  password text not null,
  remember_token text,
  role text not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users
  add column if not exists role text not null default 'user';

-- ---------------------------------------------------------------------------
-- password_reset_tokens (enlaces de recuperación)
-- ---------------------------------------------------------------------------
create table if not exists public.password_reset_tokens (
  email text primary key,
  token text not null,
  created_at timestamptz
);

-- ---------------------------------------------------------------------------
-- email_notifications (registro de correos enviados)
-- ---------------------------------------------------------------------------
create table if not exists public.email_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users (id) on delete set null,
  email text not null,
  type text not null,
  subject text not null,
  status text not null default 'sent',
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists email_notifications_email_type_idx
  on public.email_notifications (email, type);

-- ---------------------------------------------------------------------------
-- sessions (sesiones web de Laravel)
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  id text primary key,
  user_id bigint,
  ip_address text,
  user_agent text,
  payload text not null,
  last_activity integer not null
);

create index if not exists sessions_user_id_idx on public.sessions (user_id);
create index if not exists sessions_last_activity_idx on public.sessions (last_activity);

comment on table public.users is 'Cuentas de login (Laravel): paciente (user) o administrador (admin).';
comment on table public.email_notifications is 'Historial de correos enviados (p. ej. reset de contraseña).';
comment on table public.password_reset_tokens is 'Tokens temporales para restablecer contraseña.';
